### ISSUE TITLE
PS3 Version...

### ISSUE THREAD

**Issue by marcussacana** [moosotc/dormin#1]
Hi, is possible write a nico.dat repack? some textures in HD from Shadow looks use the same ps2 game format
![http://image.prntscr.com/image/540ca35995bf4bb0899c9a4fd510e9d2.png](http://image.prntscr.com/image/540ca35995bf4bb0899c9a4fd510e9d2.png)

**Comment by moosotc** [comment]
Marcus André <notifications@github.com> writes:

> Hi, is possible write a nico.dat repack? some textures in HD from
> Shadow use the game format
                 same?

I am also not sure what you mean by repack.

> ![http://image.prntscr.com/image/540ca35995bf4bb0899c9a4fd510e9d2.png](http://image.prntscr.com/image/540ca35995bf4bb0899c9a4fd510e9d2.png)
>

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by marcussacana** [comment]
yes, srry i have a bad english..
the ps3 version have same format from ps2 game in some textures...
i like a way to rewrite the nico.dat to try use the ps3 textures in the pcsx2...

**Comment by moosotc** [comment]
Marcus André <notifications@github.com> writes:

> yes, srry i have a bad english..
> the ps3 version have same format from ps2 game in some textures...
> i like a way to rewrite the nico.dat to try use the ps3 textures in the pcsx2...
>

I see. I never figured out the internal VFS layout, so the extraction of
the resources was brute forced, Vincent Hamm is the man you need to talk
to about this particular issue of yours, he did reverse engineer the VFS
and knows much more about this.

-- 
mailto:moosotc@gmail.com

**Comment by marcussacana** [comment]
he have email? github?

**Comment by moosotc** [comment]
Marcus André <notifications@github.com> writes:

> he have email? github?
>

I'm affraid I don't have his e-mail address handy, look him up, he
reverse engineered character animation system in Kingdom Hearts (among
other things) and had some videos on youtube.

-- 
mailto:moosotc@gmail.com

**Comment by marcussacana** [comment]
hmmm
i not found here, after send he channel url plz... and thanks for all, now i close this issue

**Comment by moosotc** [comment]
Marcus André <notifications@github.com> writes:

> hmmm
> i not found here, after send he channel url plz... and thanks for all,
> now i close this issue
>

Search for Vincent Hamm on LinkedIn.

-- 
mailto:moosotc@gmail.com
